profile: dev
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: chenbin
      initiaSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    password:
    timeout: 6000ms
    cluster:
      nodes: 172.16.165.135:7001,172.16.165.135:7002,172.16.165.134:7003,172.16.165.134:7004,172.16.165.133:7005,172.16.165.133:7006,172.16.165.133:7007
    lettuce:
      pool:
        # 最大活跃连接数
        max-active: 5
        # 最大空闲连接数
        max-idle: 10
        # 最小空闲连接数
        min-idle: 0
logging:
  level:
    root: info
    com.morgan: debug
server:
  port: 8081
